version: 0.2
env:
  secrets-manager:
    DOCKERHUB_PASS: "/dockerhub/credentials:password"
    DOCKERHUB_USERNAME: "/dockerhub/credentials:username"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      #- echo "Webhook Head Ref: $CODEBUILD_WEBHOOK_HEAD_REF"
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo "CODEBUILD_WEBHOOK_HEAD_REF is $CODEBUILD_WEBHOOK_HEAD_REF"
      - echo "CODEBUILD_WEBHOOK_BASE_REF is $CODEBUILD_WEBHOOK_BASE_REF"
      - echo "CODEBUILD_SOURCE_VERSION is $CODEBUILD_SOURCE_VERSION"
      - if echo "$CODEBUILD_WEBHOOK_TRIGGER" | grep -q "tag/"; then export IMAGE_TAG=$(echo $CODEBUILD_WEBHOOK_TRIGGER | sed "s|tag/||"); else echo "No tag found, using default"; export IMAGE_TAG="latest"; fi
      - 'if echo "$CODEBUILD_WEBHOOK_HEAD_REF" | grep -q "refs/tags/"; then export IMAGE_TAG=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed "s|refs/tags/||"); else echo "No tag found, using default"; export IMAGE_TAG="latest"; fi'
      - echo "Image tag determined to be $IMAGE_TAG"
      - echo $CODEBUILD_SOURCE_VERSION
      - TAG=$(echo $CODEBUILD_SOURCE_VERSION | sed 's/^refs\/tags\///')
      - echo "Extracted tag: $TAG"
      - if [ -z "$TAG" ]; then TAG="latest"; fi
      - echo "Final tag for Docker image: $TAG"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG  -f Dockerfile.prod .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
