FROM ubuntu:latest
RUN apt update
RUN apt install python3 -y
RUN apt install python3-pip -y
RUN apt install nginx -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
WORKDIR /app
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000
# Copy entrypoint script into the image
COPY ./entrypoint.sh /
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]